// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package locales_test

import (
	"testing"

	"github.com/datasweet/format/date/locales"
	"github.com/stretchr/testify/assert"
)

type dictionary struct {
	index []uint32
	data  string
}

func TestLocalizeen(t *testing.T) {
	for ft, fi := range locales.Fields {
		for w := range fi.Widths {
			for i := range fi.Keys {
				key, ok := fi.Key(w, i)
				assert.True(t, ok, key)
				assert.NotEmpty(t, key, key)
				s := locales.Localize("en", ft, w, i)
				assert.NotEmpty(t, s, key)
			}
		}
	}
}

func TestLocalizefr(t *testing.T) {
	for ft, fi := range locales.Fields {
		for w := range fi.Widths {
			for i := range fi.Keys {
				key, ok := fi.Key(w, i)
				assert.True(t, ok, key)
				assert.NotEmpty(t, key, key)
				s := locales.Localize("fr", ft, w, i)
				assert.NotEmpty(t, s, key)
			}
		}
	}
}
